### ISSUE TITLE
Migration of existing packages in CapsulaHub

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs#25]
## General description

Managing a lot of separate repositories is adding much complexity to our workflow and many duplications of config / scripts. It's hard to maintain and for now doesn't bring additional value.

We are also missing some tools that will help us to manage this repositories.

It was decided to create a unique (capsulahub) repository that will contain all packages related to CapsulaHub (core services, services extensions, components extensions, ui library, utils, etc.).

Creation of the new repository : https://github.com/capsulajs/capsulajs/issues/31

The migration process include :
- Creation one repository (using Lerna), that will include all the existing packages from:
  - capsulahub-core (https://github.com/capsulajs/capsulahub-core)
  - capsulahub (https://github.com/capsulajs/capsulahub) (rename it to capsulahub-old for now)
  - capsulahub-extensions (https://github.com/capsulajs/capsulahub-extensions)
  - capsulahub-ui (https://github.com/capsulajs/capsulahub-ui)
  - selector-service (https://github.com/capsulajs/selector-service)
- Applying a naming convention for each type of a package.
- Common configuration (TS, prettier, lint, building, testing)

CI/CD for this repository will be done in a separate task : https://github.com/capsulajs/capsulajs/issues/29

#### Prerequisites
All currently opened PR's should be resolved in all of these repos

## Tech considerations

1) Components naming should have a convention:
  - Folder name : {componentName}-component
  - Package name : capsulahub-{componentName}-component
2) Services naming should have a convention:
  - Folder name : {serviceName}-service
  - Package name : capsulahub-{serviceName}-service
3) Everything from **capsulahub-ui** repository should be put in the package with the folderName **ui** and packageName **capsulahub-ui**.
4) workspace package (folder - workspace, packageName - capsulahub-workspace)
5) cli package  (folder - cli, packageName - capsulahub-cli)

All the repos from which the data is taken should be archived.

## Ready for implementation
- [x] External dependencies have been resolved
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] Documentation
- [x] Release notes

**Comment by stephanebenayoun** [comment]
Please note that :
- `capsulahub-rename` is temporary name until we will finish to migrate the current capsulahub repo. Then it will be rename to capsulahub.
- About services and components deployment, the option to deploy on CDN/npm or both should be possible for each one in his package.json, we want flexibility, not rules according to services/components.

**Comment by dmitriyslaym** [comment]
> Please note that :
> 
> * `capsulahub-rename` is temporary name until we will finish to migrate the current capsulahub repo. Then it will be rename to capsulahub.
> * About services and components deployment, the option to deploy on CDN/npm or both should be possible for each one in his package.json, we want flexibility, not rules according to services/components.

Done it

**Comment by stephanebenayoun** [comment]
It could be better to split this issue in 2 :

1/ Migrate all repository and common configuration
2/ Setting CI/CD for the new repository

It seems to be that it's two different task.

**Comment by dmitriyslaym** [comment]
> It could be better to split this issue in 2 :
> 
> 1/ Migrate all repository and common configuration
> 2/ Setting CI/CD for the new repository
> 
> It seems to be that it's two different task.

Agree, done.

**Comment by stephanebenayoun** [comment]
> Prerequisites
> All currently opened PR's should be resolved in all of these repos
Having this as a prerequisite is not realistic, we need to start working on the task (creating the repo, configuration, etc.) and then migrate one by one and make sure everything is closed or migrated or not relevant for migration in each repo.

**Comment by stephanebenayoun** [comment]
`capsulahub` repo doesn't need migration as we will rewrite it in https://github.com/capsulajs/capsulajs/issues/26.
So we will keep the old repo until we finish https://github.com/capsulajs/capsulajs/issues/26 and then archive it.
