### ISSUE TITLE
Build and Run commands for CapsulaHub CLI

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs#26]
## General description

CapsulaHub CLI allow user to create and launch his application using capsulaHub.
At this step the CLI will provide 2 commands :
- **capsula-hub run** to run the application locally.
- **capsula-hub build** to build the application files in a specific folder (ready to deploy)

To build and run the application, user needs to provide his configuration. CapsulaHub CLI support several configuration providers, user need to specify which one he wants to use and provide a correct token.

User should be able to specify on which port the application will run locally.
User should be able to specify on which folder the application will be built.

### **capsulahub run**
_// The token that will be used to get the configuration (required)_
**-- token**
_// The type of configuration provider (optional - default is "httpFile")_
_// Possible options: 'localFile', 'httpFile', 'scalecube', 'httpServer', 'localStorage'_
**-- configProvider;**
_// The url of the dispatcher for those providers that use dispatcher (optional)_
**-- dispatcherUrl;**
_// The port on which the application will run locally (for instance, http://localhost:5555/) (optional - default is "55555")_
**-- port;**

### **capsulahub build**
_// The token that will be used to get the configuration (required)_
**-- token**
_// The type of configuration provider (optional - default is "httpFile")_
_// Possible options: 'localFile', 'httpFile', 'hardcoreServer', 'httpServer', 'localStorage'_
**-- configProvider;**
_// The url of the dispatcher for those providers that use dispatcher (optional)_
**-- dispatcherUrl;**
_// Relative path to the output folder (optional - default is "./dist")_
**-- output;**

#### Design description

A clear and concise description of the design proposition.

- [x] Is it backward compatible ?
- [x] Adds new API
- [x] Changes existing API
- [ ] Removes existing API

## Test cases

https://github.com/capsulajs/capsulahub-old/pull/33
https://github.com/capsulajs/capsulahub-old/pull/39

## Tech consideredation
Application has to be implemented in TS.
We should make sure that run and build fails if there are TS errors.

## Ready for implementation
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes

**Comment by stephanebenayoun** [comment]
We should think about also providing a way to use `capsulahub` command with a file (like `.capsulahubrc`) that could look like this :
```js
{
  token: '...',
  configProvider: '...',
  ...
}
```
It may be useful to avoid too long commands. And as this file can be javascript, it could also give us more flexibility in arguments (not just strings).

What do you think @dmitriyslaym ?

**Comment by dmitriyslaym** [comment]
> We should think about also providing a way to use `capsulahub` command with a file (like `.capsulahubrc`) that could look like this :
> 
> ```js
> {
>   token: '...',
>   configProvider: '...',
>   ...
> }
> ```
> 
> It may be useful to avoid too long commands. And as this file can be javascript, it could also give us more flexibility in arguments (not just strings).
> 
> What do you think @dmitriyslaym ?

I think it's a great idea. I suggest to do it in a separate issue.

**Comment by Amir974** [comment]
suggested scenario to add:

```gherkin
Scenario: running multiple same build command
Given that I run a build command 
When I run the same build command again with same parameters
Then the content of the previous build in the folder is removed
And the content of the new build is added
```

**Comment by dmitriyslaym** [comment]
> suggested scenario to add:
> 
> ```
> Scenario: running multiple same build command
> Given that I run a build command 
> When I run the same build command again with same parameters
> Then the content of the previous build in the folder is removed
> And the content of the new build is added
> ```

Amir, I believe that it's a good suggestion - to make sure that we don't dublicate the same build files again.
