### ISSUE TITLE
Set CI/CD for CapsulaHub repository

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs#29]
## General description
The new `capsulaHub` repository that will include all packages related to CapsulaHub need to include a flexible and efficient CI/CD process.

~~It should allow each package to be deployed to npm or cdn or both by setting very simple configuration in the package.~~
All packages will be published to `npm` registry.  
A package could be also deployed to cdn by adding a simple configuration in its `package.json`.

This process should be applied on all existing packages in the repository and should be easy to set for any new package that will be added in the future.
 
#### NPM Publish
Automatically update the version of the package and publish it on npm registry for any branch.

For existing packages in the repository :
- Make sure that all the required exports are available from the root of the package, public api is being exported as API, types definitions are generated correctly.
- Add comment in PRs with npm version

#### CDN
Deploy to capsulaHub bucket /{package-name}

For existing packages in the repository :
- Bundled JS
- Example (JS + HTML) - if exists
- Docs - if exists
- Additional configurations - if exists
The links to the deployed versions should appear as comments to PR automatically.

#### Prerequisites
Unificated CapsulaHub repo https://github.com/capsulajs/capsulajs/issues/25

## Ready for implementation
- [x] External dependencies have been resolved
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] Manual QA
- [x] Documentation
- [x] Release notes

**Comment by MikeSquall** [comment]
For the technical considerations, the check that makes sure that what is required is available couldn't be done in the npm publishing script but should be done directly in each package.
