### ISSUE TITLE
Environment Selection component

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs#30]
## General description

This component will display a list of environments and allow to :
- Select an environment (click on the item in the list)
- Connect to an environment (click on the circle on right side of the item)
- Disconnect from an environment (click on the circle of a connected Env or connect to another)

#### Mockup
![image](https://user-images.githubusercontent.com/28623229/59560382-ce39fe00-9019-11e9-96ed-bb9fd5bcc096.png)
x button on the right top corner is not relevant.
Style implemented here will be basic and generic, it won't precisely meet the mockup.

## API

https://github.com/capsulajs/capsulahub-extensions/pull/39

#### Design description

A clear and concise description of the design proposition.

- [x] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

## Behavior
1) The data from **"environments" prop** array is rendered in the list of envs.
2) Initially no env is selected and connected to.
3) When a user clicks on some env, **onSelect" prop** callback is triggered with the name of this environment in its argument.
4) When **"selected" prop** is passed to component and this environment name exists in the list of **"environments" prop** - this environment changes it's background in component (visually shown as selected). If this env does not exist in the list - nothing happens.
5) When a user clicks on a gray circle next to env - **"onConnect" prop** callback is triggered with the name of env that has to be connected to. The circle becomes spinning loader instead of gray color.
If this env was not selected previously - it also should act as if a user has clicked on the env - look at 3 and 4 steps.
If some env was previously connected to (had green circle) -  **"onDisconnect" prop** callback should be triggered with the name of the env in the argument.
6) If a user clicks on the green circle of already selected env - **"onDisconnect" prop** callback should be triggered with the name of this env in the argument and the loader should appear instead of the circle next to this env.
7) When **"connected" prop** is passed to component and this environment name exists in the list of **"environments" prop** - this environment changes its circle in component to green color (visually shown as connected) - loader disappears. If this env does not exist in the list or if an empty string is used as a value of the prop - the circles next to each env are gray and no loaders.

## Test cases

https://github.com/capsulajs/capsulahub-extensions/pull/42

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

**Comment by stephanebenayoun** [comment]
This component doesn’t include filter. I think that what you see in the design was filter for catalog below, but it’s not related to the environment.

To connect/disconnect click on the circle.

**Comment by dmitriyslaym** [comment]
@stephanebenayoun It looked much more like something related with env selection. But ok, I'm removing all the logic about filtering from envSelection.

Will a user be able to disconnect from an environment when he clicks on the circle of a currently connected env? (I think yes)

**Comment by dmitriyslaym** [comment]
@stephanebenayoun 
Imagine that the component is in its initial state and no env has been selected.
A user clicks on a circle for one of the envs - we connect to this env. Should we also select this env? (I think yes) OR should he click outside of the circle on the title of this environment in order to select it?

**Comment by stephanebenayoun** [comment]
Yes use should be able to disconnect on clicking on the green circle.
Clicking on the circle can also select the env in the same time, I don't see a problem with it.

**Comment by dmitriyslaym** [comment]
> Yes use should be able to disconnect on clicking on the green circle.
> Clicking on the circle can also select the env in the same time, I don't see a problem with it.

Got it.

**Comment by dmitriyslaym** [comment]
@stephanebenayoun  I have updated the behavior, please review.

**Comment by stephanebenayoun** [comment]
API and behavior seems good
